### ISSUE TITLE
Research Frameworks

### ISSUE THREAD

**Issue by chris2020** [FourthYearSW/GO-SPA#5]
Find out details about frameworks that can be used and which one is best for the project

**Comment by AndrejLavrionovic** [comment]
Working on it. Looking at Gorilla platform.

**Comment by AndrejLavrionovic** [comment]
GOrilla's research is done on very basic level. There is Wiki page created, but during the comparing different platforms found that Iris is most popular as documentation is away better. Needs discussion.

**Comment by willhogan11** [comment]
I just pasted an image on Slack, might help with decision...

**Comment by AndrejLavrionovic** [comment]
Working on Iris platform research

**Comment by AndrejLavrionovic** [comment]
I have done research for GOrilla and Iris frameworks. Closing the issue.
